### PR TITLE
 Update author names for Reposense

### PR DESCRIPTION
**Pull request by ZhuanYu**
Hi please check if your author name is correct.

### CODE REVIEW

**Comment by ZhuanYu** [comment]
Do not merge this PR UNTIL everyone has commented that their author name is correct.

**Comment by dlworldpeace** [comment]
It is generally a good practice to end a file with newline character(for your config.json in this case), because each line in a text file terminates with an "end-of-line" character--the last line shouldn't be any exception.

**Comment by Lexzt** [comment]
My names are correct and Author should be fine! However, for the config.json file, might wanna change it to proper indentation even though checkstyle might not check it.

**Comment by ZhuanYu** [comment]
> .

The file is haunted.

**Pull request merged**
